# Generated by Django 4.2.6 on 2023-11-16 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(help_text='First name', max_length=50)),
                ('last_names', models.CharField(help_text='Last name', max_length=50)),
                ('birth_dates', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('publication_dates', models.DateField(default='2000-01-01', verbose_name='publication date')),
                ('duration_field', models.FloatField()),
                ('film_genre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('website', models.URLField(default='http://www.netflix.com/pl/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Review of the movie/series.')),
                ('rating', models.IntegerField(help_text='Rating of the movie/series.')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date of writing the review.')),
                ('date_edited', models.DateTimeField(help_text='Date and time of the last review edit.', null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(help_text='Reviewed Movie/series.', on_delete=django.db.models.deletion.CASCADE, to='reviews.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Name of the role', max_length=100)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(through='reviews.MovieCasts', to='reviews.actor'),
        ),
    ]
