# Generated by Django 4.2.6 on 2023-11-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_movie_duration_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_dates',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='publication_dates',
            field=models.CharField(blank=True, default='2000-01-01', max_length=50, null=True, verbose_name='publication date'),
        ),
    ]
