# Generated by Django 4.2.6 on 2023-11-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_actor_birth_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration_field',
            field=models.CharField(blank=True, default='99', max_length=50, null=True),
        ),
    ]
