# Generated by Django 4.2.6 on 2023-11-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_movie_duration_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='duration_field',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
    ]
