# Generated by Django 4.2.6 on 2024-02-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_review_creator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieCasts',
            new_name='MovieCast',
        ),
    ]
