# Generated by Django 4.2.6 on 2024-02-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_rename_moviecasts_moviecast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='publication_dates',
        ),
    ]
