# Generated by Django 4.2.6 on 2024-02-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_remove_movie_publication_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='publication_dates',
            field=models.DateTimeField(blank=True, help_text='Publication date of the movie/series', null=True),
        ),
    ]
