# Generated by Django 4.2.6 on 2024-02-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_movie_publication_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='publication_dates',
            field=models.DateField(blank=True, help_text='Publication date of the movie/series', null=True),
        ),
    ]
